name: DeepLink input

on:
  workflow_dispatch:
    inputs:
      Environment:
        description:  'Environment (Write TI, TA or PP)'
        required: true
        default: 'PP'

jobs:
  Job1:
    name: My Job1
    runs-on: ubuntu-latest
    env:
        FIRST_NAME: MORDOJO
        TEST_ENV: ${{github.event.inputs.Environment}}
    steps:
      - name: Print EnvironmenT
        run: |
          echo Current Environment: ${{github.event.inputs.Environment}}
          echo FIRST_NAME (lower): $FIRST_NAME | tr [:upper:] [:lower:]
          echo Environment (upper): $TEST_ENV
          echo Environment (lower): $TEST_ENV | tr [:upper:] [:lower:]
