name: DeepLink input

on:
  workflow_dispatch:
    inputs:
      Environment:
        description:  'Environment (Write TI, TA or PP)'
        required: true
        default: 'PP'
        
jobs:
  Job1:
    name: My Job1
    runs-on: ubuntu-latest
    steps:
      - name: Print EnvironmenT
        env:
          FIRST_NAME: MORDOJO
        run: |
          TEST_ENV=$(echo ${{ github.event.inputs.Environment }} | tr '[:upper:]' '[:lower:]')
          echo Current Environment: ${{github.event.inputs.Environment}}
          echo $FIRST_NAME | tr [:upper:] [:lower:]
          echo $TEST_ENV
          echo mvn -dTest=data/$TEST_ENV/$TEST_ENV-manager.json
          echo mvn -dTest=data/$TEST_ENV/$TEST_ENV-manager.json
