name: DeepLink input

on:
  workflow_dispatch:
    inputs:
      Environment:
        description:  'Environment (Write TI, TA or PP)'
        required: true
        default: 'PP'

jobs:
  Job1:
    name: My Job1
    runs-on: ubuntu-latest
    env:
        FIRST_NAME: MORDOJO
        TEST_ENV: ${{github.event.inputs.Environment}} | tr [:lower:] [:upper:]
    steps:
      - name: Print EnvironmenT
        run: |
          echo Current Environment (upper): ${{github.event.inputs.Environment}}
          echo Current Environment (lower): $TEST_ENV
