name: DeepLink input

on:
  workflow_dispatch:
    inputs:
      Environment:
        description:  'Environment (Write TI, TA or PP)'
        required: true
        default: 'PP'

jobs:
  Job1:
    name: My Job1
    runs-on: ubuntu-latest
    env:
        FIRST_NAME: MORDOJO
        TEST_ENV1: ${{github.event.inputs.Environment}}
        TEST_ENV2: (${{github.event.inputs.Environment}} | tr [:upper:] [:lower:])
    steps:
      - name: Print EnvironmenT
        run: |
          echo Current Environment: ${{github.event.inputs.Environment}}
          echo Environment (upper): $TEST_ENV1
          echo Environment (lower): $TEST_ENV2
