name: Greeting from Mordojo

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: MORDOJO
          LAST_NAME: SNOUSSI
        run: |
          echo $MY_VAR $FIRST_NAME $LAST_NAME.toLowerCase()
